#!/bin/bash

echo "EA Bridge Demo - Hedge Trading System"
echo "======================================"
echo ""
echo "This demo shows two Expert Advisors communicating:"
echo "1. TestEAClient - Simulates an EA placing trades"
echo "2. TestHedgeClient - Simulates the hedge system that mirrors trades"
echo ""
echo "INSTRUCTIONS:"
echo "1. The Hedge Client is already running in the background"
echo "2. Now start the EA Client in a new terminal with:"
echo "   mvn exec:java -Dexec.mainClass=\"com.orbtl.eabridge.TestEAClient\" -Dexec.classpathScope=test"
echo ""
echo "3. In the EA Client, try these commands:"
echo "   - BUY EURUSD 0.1    (opens a buy position)"
echo "   - SELL GBPUSD 0.2   (opens a sell position)"
echo "   - STATUS            (sends account status)"
echo "   - CLOSE 1000        (closes position with ticket 1000)"
echo "   - QUIT              (exits the client)"
echo ""
echo "The Hedge Client will automatically:"
echo "- Receive trade signals from the EA"
echo "- Place opposite trades (BUY becomes SELL, SELL becomes BUY)"
echo "- Send confirmations back to the EA"
echo ""
echo "Watch both terminals to see the real-time communication!"